language: node_js

node_js:
- "lts/*"
- "node"

install:
- npm ci
# keep the npm cache around to speed up installs
cache:
  directories:
  - "$HOME/.npm"

script:
- npm run lint
- TWITTER_CONSUMER_KEY= npm test
- npm run dist

jobs:
  include:
  - stage: release
    if: |
      repo = 'Mogztter/asciidoctor-tweet' AND \
      tag IS present
    script: ./tasks/package.sh
    deploy:
    - provider: npm
      skip_cleanup: true
      email: ${NPM_USER_EMAIL}
      api_key: ${NPM_USER_API_KEY}
      on:
        tags: true
    - provider: releases
      api_key: ${GITHUB_TOKEN}
      file: bin/asciidoctor-tweet.dist.*
      skip_cleanup: true
      file_glob: true
      on:
        tags: true
